import { TemplateResult } from 'lit';
export declare const voltageLevelIcon: TemplateResult<1>;
export declare const bayIcon: TemplateResult<1>;
export declare const powerTransformerTwoWindingIcon: TemplateResult<1>;
export declare const generalConductingEquipmentIcon: TemplateResult<1>;
export declare const disconnectorIcon: TemplateResult<1>;
export declare const circuitBreakerIcon: TemplateResult<1>;
export declare const currentTransformerIcon: TemplateResult<1>;
export declare const voltageTransformerIcon: TemplateResult<1>;
export declare const earthSwitchIcon: TemplateResult<1>;
export declare const infeedingLine: TemplateResult<1>;
export declare const synchronousMachine: TemplateResult<1>;
export declare const motor: TemplateResult<1>;
export declare const line: TemplateResult<1>;
export declare const neutralResistor: TemplateResult<1>;
export declare const reactor: TemplateResult<1>;
export declare const capacitor: TemplateResult<1>;
export declare const generator: TemplateResult<1>;
export declare const powerCable: TemplateResult<1>;
export declare const surgeArresterIcon: TemplateResult<1>;
export declare function crossProduct<T>(...arrays: T[][]): T[][];
export declare function typeStr(condEq: Element): string;
export declare function getIcon(condEq: Element): TemplateResult;
